//
//  Storyline.swift
//  jasmer
//
//  Created by Vivian Kosasih on 03/08/21.
//

import Foundation
import UIKit

struct Storyline{
    let personName: String?
    let conversationText: String?
    let personImage1: UIImage?
    let personImage2: UIImage?
    let backgroundImage: UIImage?
    let talkingPerson: TalkingPerson?
    let category: Category
    let interactions: [String?: Int?]
    let correctText: String?
    let wrongText: String?
    let correctAnswer: String?
    let moveToSection: Int?
    var previousSection: Int?
    var previousIndex: Int?
    let needItalics: Bool?
    let isLast: Bool?
    let isFirst: Bool?
    let currentSprite: SpriteType?
    let nextSprite: SpriteType?

    init(personName: String?, conversationText: String?, personImage1: UIImage?, personImage2: UIImage?, backgroundImage: UIImage?, talkingPerson: TalkingPerson?, category: Category, interactions: [String? : Int?], correctText: String?, wrongText: String?, correctAnswer: String?, moveToSection: Int?, previousSection: Int?, previousIndex: Int?, needItalics: Bool?, isLast: Bool?, isFirst: Bool?, currentSprite: SpriteType?, nextSprite: SpriteType?){
        self.personName = personName
        self.conversationText = conversationText
        self.personImage1 = personImage1
        self.personImage2 = personImage2
        self.backgroundImage = backgroundImage
        self.talkingPerson = talkingPerson
        self.category = category
        self.interactions = interactions
        self.correctText = correctText
        self.wrongText = wrongText
        self.correctAnswer = correctAnswer
        self.moveToSection = moveToSection
        self.previousSection = previousSection
        self.previousIndex = previousIndex
        self.needItalics = needItalics
        self.isLast = isLast
        self.isFirst = isFirst
        self.currentSprite = currentSprite
        self.nextSprite = nextSprite
    }
    
    public static func initializeData() -> [[Storyline]]{
        let storylines: [[Storyline]] = [
            //Section 0
            [
                Storyline(personName: "Jason", conversationText: "Ma, aku berangkat ya!!!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: true, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Mama Jason", conversationText: "Iya, salam dulu sini, nak.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil,needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Jason", conversationText: "Oh ya, Ma, hari ini terakhir buat bayar buku.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Mama Jason", conversationText: "Ya ampun hampir lupa, ini uangnya ya nak.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil,needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Mama Jason", conversationText: "Eh, itu jam siapa kamu pake? Kamu ga ngambil punya orang kan?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Jason", conversationText: "Engga, ini dari paket yang kemaren aku dapetin.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Mama Jason", conversationText: "Hmm.. Yaudah sekarang kamu berangkat. Nanti kamu telat.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Jason", conversationText: "Ehehe, iya. Dahh maa!!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: nil, conversationText: "... Jason berangkat ke sekolah.", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "homebg"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: 1, previousSection: nil, previousIndex: nil, needItalics: true, isLast: true, isFirst: false, currentSprite: .present, nextSprite: .present)
            ],
            //Section 1
            [
                Storyline(personName: "Jason", conversationText: "Ah... paket yang kemaren dari siapa ya? Kenapa kirimnya ke aku?", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: true, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Carlos", conversationText: "Jason, jadi bayar buku gak?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Jason", conversationText: "Oh, iya jadi! Tunggu sebentar!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Jason", conversationText: "Nanti aku pikirkan lagi. Juga maksud dari kotak tersebut", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: true, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: nil, conversationText: "... Jason berjalan menuju kantor administrasi sekolah.", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: 2, previousSection: nil, previousIndex: nil, needItalics: true, isLast: true, isFirst: false, currentSprite: .present, nextSprite: .present)
            ],
            //Section 2
            [
                Storyline(personName: "Jason", conversationText: "Permisi pak, selamat siang. Saya ingin membayar uang buku.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Admin"), backgroundImage: UIImage(named: "ruanggurubg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: true, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Admin", conversationText: "Oh tunggu sebentar, atas nama siapa ya?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Admin"), backgroundImage: UIImage(named: "ruanggurubg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Jason", conversationText: "Jason Nugroho, pak. Ini uangnya, pak.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Admin"), backgroundImage: UIImage(named: "ruanggurubg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Admin", conversationText: "Oh, iya. Ini lebih uangnya. Sebentar ya.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Admin"), backgroundImage: UIImage(named: "ruanggurubg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Admin", conversationText: "Ini kembaliannya ya, nak. Makasih, nak.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Admin"), backgroundImage: UIImage(named: "ruanggurubg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: nil, conversationText: "... Jason keluar dari kantor administrasi.", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "ruanggurubg"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: 3, previousSection: nil, previousIndex: nil, needItalics: true, isLast: true, isFirst: false, currentSprite: .present, nextSprite: .present)
            ],
            // Section 3
            [
                Storyline(personName: "Carlos", conversationText: "Jason!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: true, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Carlos", conversationText: "Besok lo masuk, kan?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Jason", conversationText: "Kenapa, Car?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Carlos", conversationText: "Gue… mau minta tolong dong…", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Jason", conversationText: "Minta tolong apa?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Carlos", conversationText: "Hehe… Besok tolong absenin gue dong..", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Jason", conversationText: "Ohh.. emang besok lo mau ngapain?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Carlos", conversationText: "Hmm.. biasalah! Ya?? Ayolah, nanti gue beliin skin game deh!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Jason", conversationText: nil, personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .interaction, interactions: ["Hmm, ga ah, gila ya lo?" : 4, "Beneran, nih?" : 5, "Hm.. gimana ya.." : 7], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present)
            ],
            // Section 4
            [
                Storyline(personName: "Jason", conversationText: "Hmm, ga ah, gila ya lo?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Carlos", conversationText: "Serius ini. Please?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Jason", conversationText: nil, personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .interaction, interactions: ["Ga dulu, deh, Car" : 6, "Hm.. gimana ya..":7], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present)
            ],
            //Section 5 - Hoegeng
            [
                Storyline(personName: "Jason", conversationText: "Beneran, nih?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Carlos", conversationText: "Iya, beneran!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Jason", conversationText: "Okay, ntar gue kasih tau skinnya ya!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Carlos", conversationText: "Siapp. Thanks, Son!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: nil, conversationText: "........Carlos meninggalkan Jason", personImage1: nil, personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: 10, previousSection: nil, previousIndex: nil, needItalics: true, isLast: true, isFirst: false, currentSprite: .present, nextSprite: .present)
            ],
            //Section 6 - Hatta
            [
                Storyline(personName: "Jason", conversationText: "Ga dulu, deh, Car", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Carlos", conversationText: "Yah.. yaudah. Gue nanya yang lain dulu", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: nil, conversationText: "........Carlos meninggalkan Jason", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: 16, previousSection: nil, previousIndex: nil, needItalics: true, isLast: true, isFirst: false, currentSprite: .present, nextSprite: .present)
            ],
            //Section 7
            [
                Storyline(personName: "Jason", conversationText: "Hm.. gimana ya..", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Carlos", conversationText: "Please?? Soalnya besok ada event nih!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Jason", conversationText: nil, personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .interaction, interactions: ["Sorry Car, Ga dulu ya":8, "Tambahin es doger ya?" : 9], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present)
            ],
            //Section 8 - Hatta
            [
                Storyline(personName: "Jason", conversationText: "Sorry, Car. Ga dulu ya", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Carlos", conversationText: "Yah.. yaudah. Gue nanya yang lain dulu", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: nil, conversationText: "........Carlos meninggalkan Jason", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: 16, previousSection: nil, previousIndex: nil, needItalics: true, isLast: true, isFirst: false, currentSprite: .present, nextSprite: .present)
            ],
            //Section 9 - Hoegeng
            [
                Storyline(personName: "Jason", conversationText: "Tambahin es doger ya?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Carlos", conversationText: "Iya, siap!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Jason", conversationText: "Okay, ntar gue kasih tau skinnya ya!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: "Carlos", conversationText: "Siapp. Thanks, Son!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .present),
                Storyline(personName: nil, conversationText: "........Carlos meninggalkan Jason", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "smpbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: 10, previousSection: nil, previousIndex: nil, needItalics: true, isLast: true, isFirst: false, currentSprite: .present, nextSprite: .present)
            ],
            //Section 10 - Es Doger versi Hoegeng
            [
                Storyline(personName: "Jason", conversationText: "Panas-panas gini es doger enak juga ya.", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: true, currentSprite: .present, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Eh tapi kan uang jajanku udah abis… apa pake uang lebih tadi ya?", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Ahh aku beli deh–", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Loh? Tukang es dogernya kemana?", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "esdogerpastbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: 11, previousSection: nil, previousIndex: nil, needItalics: false, isLast: true, isFirst: false, currentSprite: .present, nextSprite: .hoegeng)
            ],
            //Section 11 - Hoegeng past
            [
                Storyline(personName: "Jason", conversationText: "......", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "esdogerpastbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: true, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Hoegeng", conversationText: "Kamu! Ikut saya ke kantor polisi!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "esdogerpastbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Maaf, pak. Ada masalah apa ya pak?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Hoegeng", conversationText: "Ngapain kamu melamun ditengah jalan? Kamu tinggal dimana dek?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Saya tinggal di Apartemen Mediterania, Taman Anggrek, Pak.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Hoegeng", conversationText: "Disitu ngga ada apa-apa loh. Jujur sama saya.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Saya jujur pak. Dari saya lahir tahun 2007, saya sudah tinggal disana.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Hoegeng", conversationText: "Jangan bohong sama saya, dek. Coba kamu lihat.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: nil, conversationText: nil, personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "hoegengQuiz"), talkingPerson: nil, category: .miniGames, interactions: ["1955" : 12, "2021" : 12, "1945" : 12, "2001" : 12], correctText: "Saat ini Jason sedang berada di tahun 1955, tahun pertama kali diadakannya pemilu.", wrongText: "Pemilu pertama dilangsungkan pada tahun 1955. Jason sekarang berada di tahun tersebut.", correctAnswer: "1955", moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng)
            ],
            //Section 12
            [
                Storyline(personName: "Jason", conversationText: "Hah?! Tahun 1955?!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Hah?! Tahun 1955?!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Eh ini muka pak polisinya kok kayak familiar, ya?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: true, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Jangan jangan bapak… Pak Hoegeng.. Pak Hoegeng Imam Santoso?!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Hoegeng", conversationText: "Iya, betul", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Wah, keren banget… polisi paling jujur di Indonesia...", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Hoegeng", conversationText: "Kamu bilang apa?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Oh, bukan apa-apa, pak. Saya hanya asal bicara.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Mumpung ketemu hoegeng, tanya-tanya kali ya?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: true, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Oh ya pak, Boleh tahu ga, tugas bapak ngapain aja?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Hoegeng", conversationText: "Yah... hanya tugas biasa seperti polisi... tahu kan? Menegakkan hukum untuk melindungi masyarakat dari tindakan kriminal.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Kok bisa ya pak, orang bertindak seperti itu?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Hoegeng", conversationText: "Yah, bisa karena berbagai alasan. Namun, kebanyakan mereka seperti itu karena biasa tidak jujur.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Hoegeng", conversationText: "Seperti pengalaman saya baru-baru ini dengan salah satu pengusaha yang mau memberikan saya mobil mewah dan rumah mewah..", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "penyuapanbg1"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Hoegeng", conversationText: "Mungkin terdengar seperti itu, tapi kamu perlu tahu bahwa mereka memberikan barang-barang itu dengan maksud yang tersembunyi.", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "penyuapanbg1"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Maksud yang tersembunyi bagaimana pak? Bukannya mereka hanya dermawan?", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "penyuapanbg1"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Hoegeng", conversationText: "Dalam kasus ini tidak, dek. Mereka melakukan itu karena ingin saya menutupi tindak kriminal mereka. Hal ini disebut penyuapan.", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "penyuapanbg2"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Hoegeng", conversationText: "Jika saya adalah kriminal, saya akan menerima suapan itu. Namun, saya adalah polisi yang memiliki prinsip. Dan salah satu tugas polisi adalah menegakkan hukum.", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "penyuapanbg2"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Hoegeng", conversationText: "Saya menolak \"hadiah-hadiah\" tersebut. Karena menerima suapan adalah salah satu tindakan yang tidak jujur.", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "penyuapanbg3"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Hoegeng", conversationText: "Ingat, selesaikan tugas dengan kejujuran, karena kita masih bisa makan nasi pakai garam.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Wah… keren.. Biasanya cuma liat kata-kata itu di buku-buku...", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Wah… keren.. Biasanya cuma liat kata-kata itu di buku-buku...", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Hoegeng", conversationText: "Buku?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "Eh, Tidak, pak. Terimakasih ceritanya, saya akan coba untuk lebih jujur lagi..", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Hoegeng", conversationText: "Bagus. Kamu sudah bisa pergi. Ingat kata-kata saya tadi ya. ", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: nil, conversationText: "...Hoegeng pergi meninggalkan Jason", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hoegeng"), backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: true, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: nil, conversationText: "Bip! Bip!", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "kantorhoegengbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: true, isLast: false, isFirst: false,currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: nil, conversationText: nil, personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "kembalibg1"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: "Jason", conversationText: "...... Waktunya kembali? Ternyata jam tangan aneh ini yang membuat aku ke masa lalu?", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "kembalibg2"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: nil, conversationText: nil, personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "kembalibg3"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng),
                Storyline(personName: nil, conversationText: nil, personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "kembalibg3"), talkingPerson: nil, category: .interaction, interactions: ["Berbuat jujur" : 13, "Menolak berbuat jujur": 14], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng)
            ],
            //Section 13
            [
                Storyline(personName: nil, conversationText: "Jason berhasil kembali ke masa kini.", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "blackout"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: 15, previousSection: nil, previousIndex: nil, needItalics: true, isLast: true, isFirst: false, currentSprite: .hoegeng, nextSprite: .presentAfterPast)
            ],
            //Section 14
            [
                Storyline(personName: nil, conversationText: "Jason terjebak di Medan, 1955. Tampaknya, masih ada hal yang belum ia mengerti.", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "blackout"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: 11, previousSection: nil, previousIndex: nil, needItalics: true, isLast: false, isFirst: false, currentSprite: .hoegeng, nextSprite: .hoegeng)
            ],
            //Section 15
            [
                Storyline(personName: "Mas Doger", conversationText: "Dek, jadi beli, nggak?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "EsDoger"), backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: true, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Jason", conversationText: "Hm.. maaf pak, lain waktu saja ya... makasih ya pak.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "EsDoger"), backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: true, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast)
            ],
            //Section 16 - Es doger versi Hatta
            [
                Storyline(personName: "Jason", conversationText: "Panas-panas gini es doger enak juga ya.", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: true, currentSprite: .present, nextSprite: .hatta),
                Storyline(personName: "Jason", conversationText: "Eh tapi kan uang jajanku udah abis… apa pake uang lebih tadi ya?", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .hatta),
                Storyline(personName: "Jason", conversationText: "Ahh aku beli deh–", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .present, nextSprite: .hatta),
                Storyline(personName: "Jason", conversationText: "Loh? Tukang es dogernya kemana?", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "esdogerpastbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: 11, previousSection: nil, previousIndex: nil, needItalics: false, isLast: true, isFirst: false, currentSprite: .present, nextSprite: .hatta)
            ],
            //Section 17
            [
                Storyline(personName: "Jason", conversationText: "Permisi, pak. Ini dimana ya?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "OrangRandom"), backgroundImage: UIImage(named: "esdogerpastbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: true, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Pak J", conversationText: "Di Irian Barat, dek.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "OrangRandom"), backgroundImage: UIImage(named: "esdogerpastbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Jason", conversationText: "Irian Barat... makasudnya Papua?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "OrangRandom"), backgroundImage: UIImage(named: "esdogerpastbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: true, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: nil, conversationText: nil, personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "hattaQuiz"), talkingPerson: nil, category: .miniGames, interactions: ["1963-1973": 18, "2002-Sekarang":18, "1973-2001": 18, "1946-1963" : 18], correctText: "Saat ini Jason sedang berada di antara tahun 1963-1973, saat Papua masih disebut Irian Barat.", wrongText: "Nama Irian diganti menjadi Irian Barat secara resmi sejak 1 Mei 1963 sampai 1973.", correctAnswer: "1963-1973", moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta)
            ],
            //Section 18
            [
                Storyline(personName: "Jason", conversationText: "Memangnya ini tahun berapa, Pak?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "OrangRandom"), backgroundImage: UIImage(named: "esdogerpastbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Pak J", conversationText: "Tahun? 1970, dek", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "OrangRandom"), backgroundImage: UIImage(named: "esdogerpastbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Jason", conversationText: "Oh, begitu... makasih ya, Pak.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "OrangRandom"), backgroundImage: UIImage(named: "esdogerpastbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Jason", conversationText: "Kenapa aku disini ya? Aduh...", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "esdogerpastbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: true, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Jason", conversationText: "Oh, itu ada lapangan terbang!", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "esdogerpastbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Jason", conversationText: "Loh? Itu kok ada pak Muhammad Hatta? Apa benar ini tahun 1970?", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "bandarabg1"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: true, isFirst: false, currentSprite: .hatta, nextSprite: .hatta)
            ],
            //Section 19
            [
                Storyline(personName: "Jason", conversationText: "Permisi, pak. Selamat siang. Apakah bapak Mohammad Hatta?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: true, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Oh, betul. Namamu... Jason?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Kok kamu pakai baju sekolah?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Jason", conversationText: "Saya habis pulang sekolah pak, terus nggak sengaja lihat bapak. Saya senang sekali bisa ketemu Wakil Presiden Indonesia!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Wah, kamu belum tahu ya? Saya sudah tidak menjabat sebagai Wakil Presiden.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Jason", conversationText: "Oh iya, Pak? Maaf.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Iya, sekarang saya cuma rakyat biasa. Tapi, tidak soal siapapun kita, kita semua mau yang terbaik buat saudara-saudara kita.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Contohnya tadi. Baru saja sebelum saya duduk disini ada yang mau memberi saya uang.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Memang keinginannya baik, dia bukan mau mengkorupsi saya. Tapi, ternyata uang itu milik rakyat Irian Barat.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Jason", conversationText: "Maksudnya bagaimana pak?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Jadi tadi siang ada seorang pria yang mengatur kunjungan kedatangan saya, dia ingin memberi uang ke saya.", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "penyuapanbg4"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Ternyata uang tersebut bukan uang pribadinya. .", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "penyuapanbg4"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Itu uang sumbangan dari rakyat Papua.", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "penyuapanbg4"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Saya tahu mana yang hak saya dan mana yang bukan. ", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "penyuapanbg4"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Dengan prinsip itu, saya menolak pemberian uang tersebut.", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "penyuapanbg5"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Saya bilang itu uang rakyat. Lagipula saya juga sudah diberikan biaya-biaya lain yang sudah ditanggung oleh pihak penyelenggara acara. ", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "penyuapanbg5"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Jika saya menerima uang tersebut, saya sudah bertindak tidak jujur. Tidak jujur pada rakyat.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Padahal, kejujuran adalah suatu sifat yang sangat penting.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Ingat, \"kurang cerdas dapat diperbaiki dengan belajar, kurang cakap dapat dihilangkan dengan pengalaman. Namun, tidak jujur sulit diperbaiki.\"", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Jason", conversationText: "Keren…", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Nah, sepertinya saya permisi harus pergi dulu.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Jason", conversationText: "Wah, sayang sekali. Tapi Terima kasih atas waktunya, pak.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Sama-sama Jason. Terimakasih sudah mendengarkan. Nah, sebelum kita berpisah saya mau bertanya.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Apakah menurut kamu, sesuatu yang bagus itu harus didapatkan dengan uang?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Jason", conversationText: nil, personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person1, category: .interaction, interactions: ["Harus dengan uang" :20, "Tidak harus dengan uang" : 21], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta)
            ],
            //Section 20
            [
                Storyline(personName: "Jason", conversationText: "Harus dengan uang", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Hatta", conversationText: "Baiklah. Sampai jumpa.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Jason", conversationText: "Terima kasih banyak. Sampai jumpa, Pak!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Jason", conversationText: "Bip! Bip!", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "kembalibg5"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: true, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: "Jason", conversationText: "Bunyi apa ini? Jangan-jangan jam tangan aneh ini yang membuat aku ke masa lalu?", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "kembalibg5"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: nil, conversationText: nil, personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "kembalibg6"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .hatta),
                Storyline(personName: nil, conversationText: "Jason terjebak di Papua, 1970. Tampaknya, masih ada hal yang belum ia mengerti.", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "blackout"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: 17, previousSection: nil, previousIndex: nil, needItalics: true, isLast: true, isFirst: false, currentSprite: .hatta, nextSprite: .hatta)
            ],
            //Section 21
            [
                Storyline(personName: "Jason", conversationText: "Tidak harus dengan uang", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .presentAfterPast),
                Storyline(personName: "Hatta", conversationText: "Baiklah. Sampai jumpa.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .presentAfterPast),
                Storyline(personName: "Jason", conversationText: "Terima kasih banyak. Sampai jumpa, Pak!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Hatta"), backgroundImage: UIImage(named: "bandarabg2"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .presentAfterPast),
                Storyline(personName: "Jason", conversationText: "Bip! Bip!", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "kembalibg5"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: true, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .presentAfterPast),
                Storyline(personName: "Jason", conversationText: "Bunyi apa ini? Jangan-jangan jam tangan aneh ini yang membuat aku ke masa lalu?", personImage1: UIImage(named: "Jason"), personImage2: nil, backgroundImage: UIImage(named: "kembalibg5"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .presentAfterPast),
                Storyline(personName: nil, conversationText: nil, personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "kembalibg6"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .hatta, nextSprite: .presentAfterPast),
                Storyline(personName: nil, conversationText: "Jason berhasil kembali ke masa kini.", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "blackout"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: 15, previousSection: nil, previousIndex: nil, needItalics: true, isLast: true, isFirst: false, currentSprite: .hatta, nextSprite: .presentAfterPast)
            ],
            //Section 22
            [
                Storyline(personName: nil, conversationText: "...Carlos datang", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: true, isLast: false, isFirst: true, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Carlos", conversationText: "Eh Jason! Belom pulang?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Jason", conversationText: "Eh iya, belom. Lo belum balik?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Carlos", conversationText: "Ini mau balik, kok. Oh lo mau dibeliin es doger ya?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Jason", conversationText: "Oh ya soal itu. Gue ga bisa absenin lo besok!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Carlos", conversationText: "Loh? Kenapa?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Jason", conversationText: "Itu sama aja gue ngebiarin lo bertindak ga baik.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Jason", conversationText: "Mending besok lo dateng, siapa tau ada ulangan dadakan", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Carlos", conversationText: "Heh! Sembarangan. Tapi bener juga.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Carlos", conversationText: "Oke, deh Jason. Gapapa. Makasih ya, udah ingetin gue.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Jason", conversationText: "Iya, sama sama. Yaudah gue balik dulu yaa. Bye Carlos", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Carlos", conversationText: "Bye, Son", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: nil, conversationText: "Carlos dan Jason pulang ke rumah masing-masing.", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "esdogerbg"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: 23, previousSection: nil, previousIndex: nil, needItalics: true, isLast: true, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast)
            ],
            //Section 23
            [
                Storyline(personName: "Jason", conversationText: "Maa, aku pulang.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: true, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Mama Jason", conversationText: "Ehh, anak mama udah pulang. Gimana sekolahnya?.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil,needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Jason", conversationText: "Baik, maa. Oh iya, ini kembalian tadi uang buku.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Mama Jason", conversationText: "Loh, tumben? Nggak kamu pakai jajan?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil,needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Jason", conversationText: "Tadinya mau beli es doger sih, tapi aku mikir mikir lagi. Mending aku balikin duitnya ke mama dulu.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Mama Jason", conversationText: "Ya ampun… anak mama jujur sekali. Untung kamu nggak beli, nak.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Jason", conversationText: "Loh kenapa?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Mama Jason", conversationText: "Soalnya mama hari ini bikin es doger.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Jason", conversationText: "WAHHH!! Beneran, ma? Asikk!! Makasih, ma!!", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person1, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: "Mama Jason", conversationText: "Sama-sama, nak.", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "MamaJason"), backgroundImage: UIImage(named: "homebg"), talkingPerson: .person2, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast),
                Storyline(personName: nil, conversationText: "....Tamat", personImage1: nil, personImage2: nil, backgroundImage: UIImage(named: "homebg"), talkingPerson: nil, category: .conversation, interactions: [nil:nil], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: 23, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: .presentAfterPast, nextSprite: .presentAfterPast)
            ],
            //Section 24 - Kuis
            [
                Storyline(personName: "Kuis", conversationText: "Apa yang bisa kamu terapkan setelah membaca cerita tersebut?", personImage1: UIImage(named: "Jason"), personImage2: UIImage(named: "Carlos"), backgroundImage: UIImage(named: "homebg"), talkingPerson: nil, category: .postQuiz, interactions: ["Tidak menerima suap " : 1, "Jangan sembarangan membeli es doger" : 0, "Melakukan tindakan korupsi" : 0, "Jangan bicara dengan orang sembarangan" : 0], correctText: nil, wrongText: nil, correctAnswer: nil, moveToSection: nil, previousSection: nil, previousIndex: nil, needItalics: false, isLast: false, isFirst: false, currentSprite: nil, nextSprite: nil)
            ]
        ]
        
        return storylines
    }
}

enum TalkingPerson{
    case person1
    case person2
}

enum Category{
    case conversation
    case interaction
    case postQuiz
    case miniGames
}

enum StoryCase {
    case hatta
    case hoegeng
}

enum SpriteType{
    case present
    case hoegeng
    case hatta
    case presentAfterPast
}
